name: PR CI

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar pnpm
        run: npm install -g pnpm@10

      - name: Instalar dependências
        run: pnpm install --frozen-lockfile

      - name: Instalar browsers do Playwright
        run: pnpm exec playwright install --with-deps

      - name: Rodar testes E2E
        run: pnpm test:e2e

      - run: pnpm build